/******************************************************************* 
 * Header file generated by Protoc for Embedded C.                 *
 * Version 0.1 (2011-AUG-01)                                       *
 *                                                                 *
 * Copyright (c) 2009-2011                                         *
 * Technische Universitaet Muenchen                                *
 * http://www4.in.tum.de/                                          *
 *                                                                 *
 * Source : control.proto
 * Package: 
 *                                                                 *
 * Do not edit.                                                    *
 *******************************************************************/


#define MAX_REPEATED_LEN 32
#define MAX_STRING_LEN 32

/*******************************************************************
 * General functions
 *******************************************************************/

/*
 * returns the size of a length delimited message which also 
 * contains the first bytes for the length encoding.
 */
unsigned long Message_get_delimited_size(void *_buffer, int offset);

/*
 * Tests whether a message can be completely read from the given buffer at
 * the offset. The bytes [offset..offset+length-1] are interpreted.
 *
 * Returns 1 (true) if buffer[offset..offset+length-1] contains a complete
 * message or 0 (false) otherwise.
 */
int Message_can_read_delimited_from(void *_buffer, int offset, int length);


/*******************************************************************
 * Enumeration: control.proto, line 1
 *******************************************************************/
enum AxisType {
  _Roll = 1,
  _Pitch = 2,
  _Yaw = 3,
  _X = 4,
  _Y = 5,
  _Z = 6
};

/*******************************************************************
 * Enumeration: control.proto, line 10
 *******************************************************************/
enum ControlMsgType {
  _AxisSet = 1,
  _AxisGet = 2
};

/*******************************************************************
 * Message: control.proto, line 15
 *******************************************************************/

/* Maximum size of a serialized AxisSet-message, useful for buffer allocation. */
#define MAX_AxisSet_SIZE 11

/* Structure that holds a deserialized AxisSet-message. */
struct AxisSet {
  enum AxisType _axis;
  float _value;
};
/*
 * Serialize a AxisSet-message into the given buffer at offset and return
 * new offset for optional next message.
 */
int AxisSet_write_delimited_to(struct AxisSet *_AxisSet, void *_buffer, int offset);

/*
 * Deserialize a AxisSet-message from the given buffer at offset and return
 * new offset for optional next message.
 *
 * Note: All fields in _AxisSet will be reset to 0 before _buffer is interpreted.
 */
int AxisSet_read_delimited_from(void *_buffer, struct AxisSet *_AxisSet, int offset);


/*******************************************************************
 * Message: control.proto, line 21
 *******************************************************************/

/* Maximum size of a serialized AxisGet-message, useful for buffer allocation. */
#define MAX_AxisGet_SIZE 11

/* Structure that holds a deserialized AxisGet-message. */
struct AxisGet {
  enum AxisType _axis;
  float _value;
};
/*
 * Serialize a AxisGet-message into the given buffer at offset and return
 * new offset for optional next message.
 */
int AxisGet_write_delimited_to(struct AxisGet *_AxisGet, void *_buffer, int offset);

/*
 * Deserialize a AxisGet-message from the given buffer at offset and return
 * new offset for optional next message.
 *
 * Note: All fields in _AxisGet will be reset to 0 before _buffer is interpreted.
 */
int AxisGet_read_delimited_from(void *_buffer, struct AxisGet *_AxisGet, int offset);


/*******************************************************************
 * Message: control.proto, line 26
 *******************************************************************/

/* Maximum size of a serialized ControlMsgHeader-message, useful for buffer allocation. */
#define MAX_ControlMsgHeader_SIZE 29

/* Structure that holds a deserialized ControlMsgHeader-message. */
struct ControlMsgHeader {
  enum ControlMsgType _type;
  signed long _length;
  signed long _crc;
};
/*
 * Serialize a ControlMsgHeader-message into the given buffer at offset and return
 * new offset for optional next message.
 */
int ControlMsgHeader_write_delimited_to(struct ControlMsgHeader *_ControlMsgHeader, void *_buffer, int offset);

/*
 * Deserialize a ControlMsgHeader-message from the given buffer at offset and return
 * new offset for optional next message.
 *
 * Note: All fields in _ControlMsgHeader will be reset to 0 before _buffer is interpreted.
 */
int ControlMsgHeader_read_delimited_from(void *_buffer, struct ControlMsgHeader *_ControlMsgHeader, int offset);
